/*
 * generated by Xtext
 */
package at.ac.tuwien.big.servicelang.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;


public class AbstractServiceValidator extends at.ac.tuwien.big.autoedit.xtext.DynamicValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.example.org/serviceexample"));
		return result;
	}
}
