/*
 * generated by Xtext
 */
package at.ac.tuwien.big.servicelang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider;

import at.ac.tuwien.big.autoedit.xtext.DynamicReferenceProposalProvider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ServiceUiModule extends at.ac.tuwien.big.servicelang.ui.AbstractServiceUiModule {
	public ServiceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	


	@Override
	public Class<? extends org.eclipse.xtext.ui.editor.quickfix.IssueResolutionProvider> bindIssueResolutionProvider() {
		return  at.ac.tuwien.big.autoedit.xtext.DynamicQuickfixProvider.class;
	}
	
	public Class<? extends AbstractJavaBasedContentProposalProvider.ReferenceProposalCreator> bindAbstractJavaBasedContentProposalProvider$ReferenceProposalCreator() {
		return DynamicReferenceProposalProvider.class;
	}

}
